name: Build Spring Maven Project

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Maven Build with Java 8
    runs-on: self-hosted

    steps:
      # Step 1: Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java 8
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: maven

      # Step 3: Build Maven project
      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to Tomcat
        run: |
          echo "Deploying WAR to Tomcat..."
           curl -v -u ${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }} \
          -T /home/ec2-user/actions-runner/_work/spring3/spring3/target/spring3-mvc-maven-xml-hello-world-1.0-SNAPSHOT.war \
          "http://ec2-3-90-210-247.compute-1.amazonaws.com:8081/manager/text/deploy?path=/spring&update=true"

      # Step 5: Publish to Nexus manually
      - name: Publish WAR to Nexus
        run: |
          mvn deploy:deploy-file \
            -Durl=http://100.31.110.202:8081/repository/github-spring/ \
            -DrepositoryId=nexus \
            -Dfile=/home/ec2-user/actions-runner/_work/spring3/spring3/target/github-spring-1.0.0.war \
            -DgroupId=com.mkyong \
            -DartifactId=spring3-mvc-maven-xml-hello-world \
            -Dversion=1.0-SNAPSHOT \
            -Dpackaging=war
