name: Build Spring Maven Project

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Maven Build with Java 8
    runs-on: self-hosted

    steps:
      # Step 1: Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java 8
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: maven

      # Step 3: Build Maven project
      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to Tomcat
        run: |
          echo "Deploying WAR to Tomcat..."
          curl -v -u admin:admin\
          -T /home/ec2-user/actions-runner/_work/spring3/spring3/target/spring3-mvc-maven-xml-hello-world-1.0-SNAPSHOT.war \
          "http://ec2-3-90-210-247.compute-1.amazonaws.com:8081//manager/text/deploy?path=/spring&update=true"
